I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 68, in script
    $ game = Game()
  File "game/script.rpy", line 68, in <module>
    $ game = Game()
  File "game/script.rpy", line 16, in __init__
    self.npc_name = self.get_npc_in_scene()
  File "game/script.rpy", line 27, in get_npc_in_scene
    npc = list(self.scene['NPCs'])[0]
AttributeError: 'Game' object has no attribute 'scene'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 68, in script
    $ game = Game()
  File "/home/carl/Pretence/renpy-8.1.1-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/home/carl/Pretence/renpy-8.1.1-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 68, in <module>
    $ game = Game()
  File "game/script.rpy", line 16, in __init__
    self.npc_name = self.get_npc_in_scene()
  File "game/script.rpy", line 27, in get_npc_in_scene
    npc = list(self.scene['NPCs'])[0]
AttributeError: 'Game' object has no attribute 'scene'

Linux-5.19.0-46-generic-x86_64-with-glibc2.35 x86_64
Ren'Py 8.1.1.23060707
CallumTest 1.0
Wed Jul 19 19:59:02 2023
